server:
  port: 8090
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动包
    url: jdbc:mysql://47.104.107.189:33306/springcloud_db01?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: yuyue520
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

  #视图配置
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# redis配置
  redis:
    host: 47.104.107.189
    port: 6379
    password: yuyue520
    timeout: 3000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-idle: 1 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-active: 4 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）


# mybatis配置
# mybatis:
#   type-aliases-package: com.yuyue.pagehelper.dto  # 所有Entity别名类所在包
#   mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
#   configuration:
#     map-underscore-to-camel-case: true  # 开启驼峰命名规则
#   config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径

# mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.yuyue.pagehelper.dto
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true





logging:
  level:
    com.yuyue.pagehelper.mapper: debug
